name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Upload .git
      uses: actions/upload-artifact@v2
      with:
        name: .git
        path: .git/
    - run: npm ci
    - run: npm run build
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Prepare project
      run: |
        npm ci
        npm run build
        npm run pack
        npm test -- --coverage || true
        mkdir -p .github/badges
    - uses: ./
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        coverage-summary-path: coverage/clover.xml
        badges-directory: .github/badges
        protected-branches: '[]'
        write-debug-logs: true
